#!/usr/bin/env bash
# Bootstrap a new brand for multi-instance BrandMover.
#
# Usage:
#   ./scripts/new_brand.sh <brand_name>
#
# Creates:
#   .env.<brand_name>           — config file (edit with your API keys)
#   brand_<brand_name>/         — brand directory (guidelines, personality, skills)
#   state_<brand_name>/         — state directory (auto-managed)

set -euo pipefail

BRAND="${1:?Usage: $0 <brand_name>}"
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

BRAND_DIR="${PROJECT_DIR}/brand_${BRAND}"
STATE_DIR="${PROJECT_DIR}/state_${BRAND}"
ENV_FILE="${PROJECT_DIR}/.env.${BRAND}"

if [ -f "$ENV_FILE" ]; then
    echo "Brand '$BRAND' already exists ($ENV_FILE)"
    exit 1
fi

echo "Setting up new brand: $BRAND"
echo "---"

# Create brand directory structure
mkdir -p "$BRAND_DIR"/{personality,prompts,references,assets,examples,skills}

# Create guidelines placeholder
cat > "$BRAND_DIR/guidelines.md" << 'GUIDELINES'
# Brand Guidelines

## BRAND IDENTITY
- **Name:** (your brand name)
- **Tagline:** (your tagline)
- **Mission:** (what you do)

## VOICE & TONE
- **Core personality traits:** professional, authentic, concise
- **Writing style:** Direct and conversational
- **Tone by content type:**
  - Announcements: Confident, clear
  - Community: Warm, inclusive
  - Educational: Helpful, expert

## VISUAL IDENTITY
- **Primary colors:** #000000, #FFFFFF
- **Background:** Dark theme preferred
- **Style:** Modern, clean

## CONTENT RULES
- Keep captions under 150 characters
- No hashtags
- Max 1 emoji per post

## NEVER USE
- "revolutionizing", "leveraging", "cutting-edge"
- Excessive exclamation marks
- Corporate jargon
GUIDELINES

# Create personality placeholder
cat > "$BRAND_DIR/personality/system_prompt.md" << 'PERSONALITY'
# Brand Agent Personality

You are a professional brand agent. You take your work seriously and produce
high-quality, on-brand content. You have opinions about what works and what
doesn't, and you're not afraid to share them respectfully.

## Default Tone
Helpful, professional, concise. You focus on results over process.

## Things to Never Say
- "I'd be happy to help!"
- "Great question!"
- "As an AI..."
PERSONALITY

cat > "$BRAND_DIR/personality/memory.md" << 'MEMORY'
# Bot Memory

## About the Operator
- (will be populated as you work together)

## Learned Patterns
- (auto-populated from feedback over time)
MEMORY

# Create skills registry
echo '{"skills": []}' > "$BRAND_DIR/skills/REGISTRY.json"

# Create state directory
mkdir -p "$STATE_DIR"

# Create .env file
cat > "$ENV_FILE" << ENVFILE
# BrandMover — ${BRAND}
# Generated by new_brand.sh

# --- LLM Provider ---
LLM_PROVIDER=anthropic
ANTHROPIC_API_KEY=
OPENAI_API_KEY=

# --- Image Generation ---
REPLICATE_API_TOKEN=
IMAGE_MODEL=auto

# --- Telegram (REQUIRED — create a new bot via @BotFather) ---
TELEGRAM_BOT_TOKEN=
TELEGRAM_ALLOWED_USER_ID=
TELEGRAM_OPERATOR_IDS=

# --- X / Twitter (create a new app at developer.x.com) ---
X_API_KEY=
X_API_SECRET=
X_ACCESS_TOKEN=
X_ACCESS_SECRET=
X_BEARER_TOKEN=

# --- Brand (points to this brand's directory) ---
BRAND_FOLDER=${BRAND_DIR}
BRAND_NAME=${BRAND}

# --- State (isolated per brand) ---
STATE_FOLDER=${STATE_DIR}
AUTO_POST_STATE_FILE=${STATE_DIR}/auto_post_state.json

# --- Agent Mode ---
AGENT_MODE=agent
AGENT_MAX_TURNS=15
AGENT_MODEL=claude-sonnet-4-6
SONNET_MODEL=claude-sonnet-4-6
HAIKU_MODEL=claude-haiku-4-5-20251001

# --- Features ---
AUTO_POST_ENABLED=false
HEARTBEAT_ENABLED=true
UNIFIED_BRAIN_ENABLED=false
INTENT_ROUTER_ENABLED=true
PREF_EXTRACTION_ENABLED=true
ENVFILE

echo ""
echo "Brand '$BRAND' created!"
echo ""
echo "Next steps:"
echo "  1. Edit $ENV_FILE — add your API keys"
echo "  2. Edit $BRAND_DIR/guidelines.md — add your brand guidelines"
echo "  3. Edit $BRAND_DIR/personality/system_prompt.md — customize personality"
echo "  4. Launch: ./scripts/launch_brand.sh $BRAND"
